name: lbc
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
- python=3.7.10
- pytorch=1.4.0
- torchvision=0.5.0
- cudatoolkit=10.1
- numpy=1.19.2
- scipy=1.5.2
- pillow=8.0.1
- tqdm=4.50.2
- notebook=6.4.0
- pandas=1.1.5
- scikit-learn=0.24.2
- pytorch-lightning=0.7.1
- efficientnet-pytorch=0.7.0
- fvcore=0.1.2.post20201122
- pip=21.0.1
- pip:
    - opencv-python==4.5.1.48
    - wandb==0.10.30
    - imgaug==0.4.0
    - py-trees==0.8.3
    - ephem==3.7.7.1
    - dictor==0.1.5
    - scikit-video==1.1.11
    - lmdb==1.2.1
    - moviepy==1.0.3
    - ray==1.1.0
    - xmlschema==1.6.2
    - pygame==2.0.1
