LOG_DIR: '/data/cornucopia/ah2029/experiments/carla/baseline'
TAG: 'baseline_transition'

GPUS: [0, 1]

BATCHSIZE: 16
PRECISION: 32
EPOCHS: 100

SEQUENCE_LENGTH: 6

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
