LOG_DIR: '/home/mifs/ah2029/experiments/carla/dreamer'
TAG: 'larger_representation_64states_2gpus'

GPUS: [0, 1]

BATCHSIZE: 20
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 5
RECEPTIVE_FIELD: 1

MODEL:
  TRANSITION:
    ENABLED: True
  PROBABILISTIC:
    ENABLED: True
  RECURRENT_MODEL:
    STATE_DIM: 64
    HIDDEN_STATE_DIM: 256
N_WORKERS: 10
