LOG_DIR: '/home/mifs/ah2029/experiments/carla/image_inputs'
TAG: '1gpu_kl=0.001_without'

GPUS: [0]

BATCHSIZE: 4
PRECISION: 32
EPOCHS: 50
N_WORKERS: 10

SEQUENCE_LENGTH: 5
RECEPTIVE_FIELD: 3

IMAGE:
  FOV: 90

MODEL:
  ENCODER:
    OUTPUT_DIM: 128
    DOWNSAMPLE_FACTOR: 16
  TRANSITION:
    ENABLED: True
  PROBABILISTIC:
    ENABLED: True
  RECURRENT_MODEL:
    STATE_DIM: 32 #64
    HIDDEN_STATE_DIM: 64 #196

LOSSES:
  WEIGHT_RECONSTRUCTION: 1.0
  WEIGHT_PROBABILISTIC: 0.001
