LOG_DIR: '/home/mifs/ah2029/experiments/carla/future_pred'
TAG: 'baseline_transition_seqlen=2'

GPUS: [0, 1]

BATCHSIZE: 18
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 2

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
