LOG_DIR: '/home/mifs/ah2029/experiments/carla/future_pred'
TAG: 'baseline_transition_seqlen=2_fp=16_temporal_model'

GPUS: [0, 1]

BATCHSIZE: 10
PRECISION: 16
EPOCHS: 50

SEQUENCE_LENGTH: 4
RECEPTIVE_FIELD: 3

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
