LOG_DIR: '/home/mifs/ah2029/experiments/carla/latent_state'
TAG: 'baseline_transition_seqlen=2_fp=16'

GPUS: [0, 1]

BATCHSIZE: 10
PRECISION: 16
EPOCHS: 50

SEQUENCE_LENGTH: 2
RECEPTIVE_FIELD: 1

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
