LOG_DIR: '/home/mifs/ah2029/experiments/carla/image_inputs'
TAG: 'image_inputs_2gpus'

GPUS: [0, 1]

BATCHSIZE: 4
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 5
RECEPTIVE_FIELD: 3

MODEL:
  ENCODER:
    OUTPUT_DIM: 128
    DOWNSAMPLE_FACTOR: 16
  TRANSITION:
    ENABLED: True
  PROBABILISTIC:
    ENABLED: True
  RECURRENT_MODEL:
    STATE_DIM: 64
    HIDDEN_STATE_DIM: 196
N_WORKERS: 10

LOSSES:
  WEIGHT_RECONSTRUCTION: 1.0
  WEIGHT_PROBABILISTIC: 0.0005
