LOG_DIR: '/home/mifs/ah2029/experiments/carla/dreamer_conv'
TAG: 'downsample=16_3gpus'

GPUS: [0, 1, 2]

BATCHSIZE: 20
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 5
RECEPTIVE_FIELD: 1

MODEL:
  ENCODER:
    OUTPUT_DIM: 256
    DOWNSAMPLE_FACTOR: 16
  TRANSITION:
    ENABLED: True
  PROBABILISTIC:
    ENABLED: True
  RECURRENT_MODEL:
    STATE_DIM: 32
    HIDDEN_STATE_DIM: 128
N_WORKERS: 10
