LOG_DIR: '/home/mifs/ah2029/experiments/carla/throttle'
TAG: 'baseline'

GPUS: [0, 1]

BATCHSIZE: 64
PRECISION: 16
EPOCHS: 50

SEQUENCE_LENGTH: 2
RECEPTIVE_FIELD: 1

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
