LOG_DIR: '/home/mifs/ah2029/experiments/carla/future_pred'
TAG: 'baseline_transition'

GPUS: [0, 1]

BATCHSIZE: 6
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 6

MODEL:
  TRANSITION:
    ENABLED: True

N_WORKERS: 10
