LOG_DIR: '/home/mifs/ah2029/experiments/carla/dreamer'
TAG: 'fix_3gpus'

GPUS: [0, 1, 2]

BATCHSIZE: 20
PRECISION: 32
EPOCHS: 50

SEQUENCE_LENGTH: 5
RECEPTIVE_FIELD: 1

MODEL:
  TRANSITION:
    ENABLED: True
  PROBABILISTIC:
    ENABLED: True

N_WORKERS: 10
