_BASE_: 'baseline.yml'

LOG_DIR: '/data/cornucopia/ah2029/experiments/carla/debug'
TAG: 'debug'

BATCHSIZE: 2
EPOCHS: 2
GPUS: [0]
LOGGING_INTERVAL: 10

DATASET:
  VERSION: 'mini'

MODEL:
  TRANSITION:
    ENABLED: True

VIS_INTERVAL: 8
