_BASE_: 'baseline.yml'

TAG: 'policy_only_mixed_precision_temporal_model'

GPUS: [0, 1]

BATCHSIZE: 36
PRECISION: 16

SEQUENCE_LENGTH: 3

MODEL:
  POLICY:
    SPEED_INPUT: False
  TRANSITION:
    ENABLED: False
