_BASE_: 'baseline.yml'

TAG: 'policy_throttle_speed_input_restriction_output_fewer_linear_layers'

GPUS: [0, 1]

BATCHSIZE: 64
EPOCHS: 100

SEQUENCE_LENGTH: 1

MODEL:
  POLICY:
    SPEED_INPUT: True
  TRANSITION:
    ENABLED: False
