_BASE_: 'baseline.yml'

TAG: 'probabilistic_temporal_2gpus'

GPUS: [0, 1]

BATCHSIZE: 36

SEQUENCE_LENGTH: 4
RECEPTIVE_FIELD: 3

MODEL:
  TEMPORAL_MODEL:
    OUTPUT_DIM: 256
  PROBABILISTIC:
    ENABLED: True


